l_korean:
 SETTING_AUTOSAVE_TO_CLOUD:0 "클라우드에 자동 저장"
 SETTING_SAVE_FILE_FORMAT:0 "기본 저장 형식"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP:0 "본 옵션은 철인, 클라우드, 디버그 모드에서만 수정할 수 있습니다."
 OPTION_SAVE_FILE_TEXT:0 "텍스트"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL:0 "잠긴 텍스트"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL:0 "잠긴 2진수"
 SETTING_TOOLTIP_MODE:0 "툴팁 모드"
 SETTING_TOOLTIP_MODE_TOOLTIP:0 "툴팁 모드"
 SETTING_TOOLTIP_MODE_NO_LOCK:0 "잠금 없음"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "마우스 움직임"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR:0 "행동 잠금 (마우스 앵커)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR:0 "시간 잠금 (마우스 앵커)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR:0 "행동 잠금"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR:0 "시간 잠금"
 SETTING_TOOLTIP_DELAY_TOOLTIP:0 "지연 시간 표시"
 SETTING_TOOLTIP_DELAY:0 "지연 시간 표시"
 SETTING_TOOLTIP_UNLOCK_TIME:0 "잠금 해제 지연 시간"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\n툴팁이 잠금 해제되기까지 걸리는 지연 시간을 설정합니다."
 SETTING_TOOLTIP_LOCK_TIME:0 "잠금 지연 시간"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\n툴팁이 잠금되기까지 걸리는 지연 시간을 설정합니다."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "잠금 후 열림 지연 시간"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:0 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\n이미 다른 툴팁이 표시된 상태에서 툴팁이 잠금되기까지 걸리는 지연 시간을 설정합니다."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "고급"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "일반"
 SETTINGS_CATEGORY_SFX:0 "개별 효과음"
 SETTINGS_CATEGORY_LANGUAGE:0 "언어"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "저장된 게임"
 SETTINGS_CATEGORY_TOOLTIPS:0 "툴팁 설정"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "지도 조작"
 SETTING_SHADER_QUALITY:0 "셰이더 품질"
 SETTING_SHADER_QUALITY_TOOLTIP:0 "#T 셰이더 품질\n#!여러 셰이더와 효과의 품질을 결정합니다.\n#X 셰이더를 컴파일하는 동안 게임에 끊김 현상이 생길 수도 있습니다.#!\n\n#T 높음:#! 퍼포먼스는 저하되지만 일부 셰이더 효과의 품질이 향상됩니다.\n\n#T 보통:#! 의도한 대로 그래픽 경험을 할 수 있는 기본 설정입니다.\n\n#T 낮음:#! 사양이 낮은 기기를 위한 설정으로, 시각 품질이 낮아지므로 권장되는 옵션은 아닙니다. 그래픽 퍼포먼스 향상을 위해 각종 셰이더가 단순화됩니다."
  # Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC:0 "음악"
 SETTING_AMBIENT:0 "환경음"
 SETTING_MUSIC_TOOLTIP:0 "#T 음악 음량\n#!음악의 음량을 설정합니다."
 SETTING_AMBIENT_TOOLTIP:0 "#T 환경음 음량\n#!환경음의 음량을 설정합니다."

 color_blind_mode_test:0 "테스트"
