l_spanish:
 SETTING_AUTOSAVE_TO_CLOUD:0 "Guardado automático en la nube"
 SETTING_SAVE_FILE_FORMAT:0 "Formato de guardado por defecto"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP:0 "Esta opción se anula en los modos de Ironman, guardado en la nube y depuración."
 OPTION_SAVE_FILE_TEXT:0 "Texto"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL:0 "Texto comprimido"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL:0 "Código en binario comprimido"
 SETTING_TOOLTIP_MODE:0 "Modo ayuda emergente"
 SETTING_TOOLTIP_MODE_TOOLTIP:0 "Modo ayuda emergente"
 SETTING_TOOLTIP_MODE_NO_LOCK:0 "Sin bloqueo"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Tendencia del ratón"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR:0 "Bloqueo por acción (anclar ratón)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR:0 "Bloqueo temporal (anclar ratón)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR:0 "Bloqueo por acción"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR:0 "Bloqueo temporal"
 SETTING_TOOLTIP_DELAY_TOOLTIP:0 "Mostrar retardo"
 SETTING_TOOLTIP_DELAY:0 "Mostrar retardo"
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Retardo de desbloqueo"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nEstablece el tiempo que tardan en desbloquearse las ayudas emergentes."
 SETTING_TOOLTIP_LOCK_TIME:0 "Retardo de bloqueo"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nEstablece el tiempo que tardan en bloquearse las ayudas emergentes."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Retardo de bloqueo abierto"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:0 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nEstablece el tiempo que tardan en bloquearse las ayudas emergentes cuando ya se está mostrando otra ayuda."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Avanzada"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "General"
 SETTINGS_CATEGORY_SFX:0 "Efectos de sonido específicos"
 SETTINGS_CATEGORY_LANGUAGE:0 "Idioma"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Partidas guardadas"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Ajustes de la ayuda emergente"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Controles de juego"
 SETTING_SHADER_QUALITY:0 "Calidad de los sombreados"
 SETTING_SHADER_QUALITY_TOOLTIP:0 "#T Calidad de los sombreados\n#!Determina la calidad de los diferentes sombreados y efectos.\n#X Es posible que el juego se bloquee al volver a compilar los sombreados.#!\n\n#T Alta:#! mejora la calidad de algunos efectos de sombreado a costa del rendimiento.\n\n#T Media:#! ajuste por defecto para disfrutar de la experiencia gráfica esperada.\n\n#T Baja:#! esta opción es perfecta para dispositivos de gama baja. No la recomendamos debido a la pérdida de calidad visual. Se simplifican diferentes sombreados para mejorar el rendimiento gráfico."
  # Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC:0 "Música"
 SETTING_AMBIENT:0 "Ambiente"
 SETTING_MUSIC_TOOLTIP:0 "#T Volumen de la música\n#!Controla el volumen de la música de fondo."
 SETTING_AMBIENT_TOOLTIP:0 "#T Volumen ambiental\n#!Controla el volumen del ambiente."

 color_blind_mode_test:0 "Prueba"
