l_turkish:
 SETTING_AUTOSAVE_TO_CLOUD:0 "Buluta otomatik kaydet"
 SETTING_SAVE_FILE_FORMAT:0 "Varsayılan kayıt biçimi"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP:0 "Bu seçenek Yıkılmaz, Bulut ve Hata Ayıklama modlarında geçersiz kılınmıştır"
 OPTION_SAVE_FILE_TEXT:0 "Metin"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL:0 "Sıkıştırılmış metin"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL:0 "Sıkıştırılmış ikili değer"
 SETTING_TOOLTIP_MODE:0 "Bilgi Kutusu Modu"
 SETTING_TOOLTIP_MODE_TOOLTIP:0 "Bilgi Kutusu Modu"
 SETTING_TOOLTIP_MODE_NO_LOCK:0 "Kilitsiz"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Fare Hassasiyeti"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR:0 "Eylem Kilidi (Fare Sabitleme)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR:0 "Zamanlayıcı Kilidi (Fare Sabitleme)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR:0 "Eylem Kilidi"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR:0 "Zamanlayıcı Kilidi"
 SETTING_TOOLTIP_DELAY_TOOLTIP:0 "Gecikmeyi Göster"
 SETTING_TOOLTIP_DELAY:0 "Gecikmeyi Göster"
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Kilit Açma Gecikmesi"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nBilgi kutusu kilidinin açılma gecikmesini belirler."
 SETTING_TOOLTIP_LOCK_TIME:0 "Kilitleme Gecikmesi"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nBilgi kutularının kilitlenme gecikmesini belirler."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Açıkken Kilitleme Gecikmesi"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:0 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nBaşka bir bilgi kutusu açıkken diğer bilgi kutularının kilitlenme gecikmesini belirler."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Gelişmiş"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Genel"
 SETTINGS_CATEGORY_SFX:0 "Belirli Ses Efektleri"
 SETTINGS_CATEGORY_LANGUAGE:0 "Dil"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Kayıtlı Oyunlar"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Bilgi Kutusu Ayarları"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Harita Kontrolleri"
 SETTING_SHADER_QUALITY:0 "Gölgelendirici Kalitesi"
 SETTING_SHADER_QUALITY_TOOLTIP:0 "#T Gölgelendirici Kalitesi\n#!Çeşitli gölgelendiricilerin ve efektlerin kalitesini belirler.\n#X Gölgelendiriciler yeniden derlenirken oyunda takılmalar yaşanabilir.#!\n\n#T Yüksek:#! Performanstan ödün vererek bazı gölgelendirici efektlerinin kalitesini yükseltir.\n\n#T Orta:#! İdeal görsel deneyim için varsayılan ayar.\n\n#T Düşük:#! Bu ayar, düşük seviye cihazlar için tasarlanmıştır ve görsel kalitede kayba neden olduğundan önerilmez. Grafik performansını arttırmak için birçok gölgelendirici efekti basitleştirilir."
  # Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC:0 "Müzik"
 SETTING_AMBIENT:0 "Ambiyans"
 SETTING_MUSIC_TOOLTIP:0 "#T Müzik Düzeyi\n#!Çalan müziklerin ses düzeyini belirler."
 SETTING_AMBIENT_TOOLTIP:0 "#T Ortam Sesleri Düzeyi\n#!Çevresel ambiyans seslerinin düzeyini belirler."

 color_blind_mode_test:0 "Test"
